In [11]:
import numpy as np
arr = np.array([1,2,3,4,5,6,2,3,3,4,5,2])
x = np.where(arr == 3)
print(x)

(array([2, 7, 8], dtype=int64),)


In [5]:
#print even
y = np.where(arr %2 == 0)
print(y)

(array([ 1,  3,  5,  6,  9, 11], dtype=int64),)


In [13]:
#print odd
z = np.where(arr %2 == 1)
print(y)

(array([ 1,  3,  5,  6,  9, 11], dtype=int64),)


In [31]:
import numpy as np
arr = np.array([1,2,3,4,5])
y = np.searchsorted(arr,3)
print(y)

2


# where replace

In [33]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
Z= np.searchsorted(arr,3, side = "right")
print(Z)

3


In [39]:
list = np.array([1,2,3,4,5,9,7,3,8,4])
list

array([1, 2, 3, 4, 5, 9, 7, 3, 8, 4])

In [43]:
ten =np.where(list>=5,10,list)
ten

array([ 1,  2,  3,  4, 10, 10, 10,  3, 10,  4])

In [47]:
five = np.where(list == 1, 20,list)
five

array([20,  2,  3,  4,  5,  9,  7,  3,  8,  4])

# reshaping array

In [55]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
y = x.reshape(2,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
y.ndim

2

In [63]:
z = np.where( y == 3)
z

(array([0], dtype=int64), array([2], dtype=int64))

In [65]:
z1 = np.where( y == 7)
z1

(array([1], dtype=int64), array([1], dtype=int64))

# sorting array

In [75]:
x = np.array([0,3,2,8,9,4])
y = np.sort(x)
des = -np.sort(-x)
print(y)
print(des)

[0 2 3 4 8 9]
[9 8 4 3 2 0]


In [77]:
d = np.sort(y)[::-1]
d

array([9, 8, 4, 3, 2, 0])

In [73]:
alp = np.array([ "s","a","b","h"])
order = np.sort(alp)
order

array(['a', 'b', 'h', 's'], dtype='<U1')

In [5]:
import numpy as np
arr = np.array([41,42,43,46])
x = [True,False,True,False]
newarray = arr[x]
newarray

array([41, 43])

# Array filter

In [15]:
aar = np.arange(1,15)
filter_array =[]
for i in aar:
    if i%2 == 0:
        filter_array.append(True)
    else:
        filter_array.append(False)
newarr = aar[filter_array]
print(newarr)

[ 2  4  6  8 10 12 14]


# Array filter

In [20]:
arr = np.arange(1,15)
filter_array = arr%2 !=0
newarr = arr[filter_array]
newarr

array([ 1,  3,  5,  7,  9, 11, 13])

# random

In [4]:
import numpy as np
c = np.random.rand(2,3)
c

array([[0.91273092, 0.98308166, 0.55802563],
       [0.61109247, 0.46701247, 0.80888758]])

### 3 dimention

In [6]:
d = np.random.rand(3,2,3)
d

array([[[0.78194192, 0.25792252, 0.90907656],
        [0.42265537, 0.34673724, 0.16284157]],

       [[0.48469931, 0.46331819, 0.97565817],
        [0.34561015, 0.3162264 , 0.66263358]],

       [[0.03937895, 0.57177428, 0.31017524],
        [0.82766086, 0.00986457, 0.23568355]]])

### 4 dimention

In [10]:
f = np.random.rand(4,3,2,3)
f

array([[[[0.0289973 , 0.14733271, 0.53377976],
         [0.37137379, 0.71096079, 0.31582115]],

        [[0.58725158, 0.07220473, 0.82064258],
         [0.47989301, 0.31175678, 0.38148877]],

        [[0.39366939, 0.33761788, 0.72737451],
         [0.29107607, 0.39380997, 0.0740107 ]]],


       [[[0.04224622, 0.93646504, 0.87341074],
         [0.55201521, 0.85229606, 0.6514907 ]],

        [[0.31249051, 0.87859991, 0.16151787],
         [0.35297401, 0.8812767 , 0.92381439]],

        [[0.12941296, 0.01436022, 0.00334208],
         [0.86479846, 0.93222198, 0.88095369]]],


       [[[0.40284681, 0.11260482, 0.3438324 ],
         [0.03448609, 0.98644172, 0.92632795]],

        [[0.20797285, 0.44122272, 0.7908411 ],
         [0.09511747, 0.40052962, 0.07372589]],

        [[0.47655617, 0.23112987, 0.81772511],
         [0.34589141, 0.4884933 , 0.16126601]]],


       [[[0.20828888, 0.87682846, 0.01031318],
         [0.60031381, 0.50253843, 0.07384001]],

        [[0.87795992, 0.73746626, 

### Random Intinger

In [12]:
f = np.random.randint(10,50,size = (4,5))
f

array([[10, 20, 18, 48, 11],
       [20, 27, 11, 46, 18],
       [28, 44, 31, 32, 38],
       [43, 15, 37, 45, 27]])

### random.unifom

In [15]:
g= np.random.uniform(1,10,5)
g

array([7.61579719, 2.68215556, 8.58476996, 4.86753148, 1.45402332])

### Normmal Distribution

In [20]:
# One dimention
h = np.random.randn(10)
h

array([ 3.19691913, -0.33943294,  1.17457555, -0.48342801,  0.55559916,
       -1.08501128, -0.12689937, -0.17623236,  0.79666069, -1.11579331])

In [22]:
# two dimention
i = np.random.randn(4,3)
i

array([[-1.47136213, -0.04860482, -0.86087526],
       [-0.90364446, -0.35476527,  0.77399761],
       [ 0.99504799,  0.44913393,  1.98465925],
       [-0.1243891 ,  0.2293529 , -0.43817506]])

In [26]:
#three Dimention
j = np.random.randn(3,4,3)
j

array([[[-0.01593483,  0.03149375,  0.38364605],
        [-0.55801788,  0.93449033, -1.14128263],
        [-2.17101983, -0.16915004, -1.04587392],
        [ 0.2096508 , -1.31169206,  1.60870126]],

       [[-0.84802837,  0.03596872,  0.21160279],
        [ 0.17198298,  0.85069019, -0.73504689],
        [ 1.20697834,  0.18289765, -2.90078586],
        [-1.75713587,  0.00982099, -0.33390663]],

       [[-0.6338362 ,  1.76225208,  0.91544623],
        [ 1.1705752 ,  2.21201175,  1.87300368],
        [-1.02919342,  1.55443492, -0.84855492],
        [ 0.28877474, -0.54982674,  0.72609616]]])

### Setting Seed

> to set uninq number in arrays

In [29]:
a = np.random.rand(5)
a

array([0.45016821, 0.34682824, 0.8888332 , 0.40349147, 0.37570729])

In [31]:
a = np.random.seed(42)
a = np.random.rand(5)
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [41]:
a = np.random.seed(42)
a = np.random.rand(5)
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [45]:
a = np.random.seed(35)
a = np.random.randint(3,9,5)
a

array([4, 7, 4, 7, 3])

In [47]:
a = np.random.seed(35)
a = np.random.randint(3,9,5)
a

array([4, 7, 4, 7, 3])

### shuffle array

In [50]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[5 3 4 1 2]
